databases:
  - name: multibliz-db
    databaseName: multiblizposdb
    user: multibliz
    plan: free
    region: oregon

services:
  - type: web
    name: multibliz-pos
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn multibliz_pos.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multibliz-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    disks:
      - name: media
        mountPath: /opt/render/project/src/media
        sizeGB: 1
