databases:
  - name: multibliz-db
    databaseName: multiblizposdb
    user: multibliz
    plan: free
    region: oregon

services:
  - type: web
    name: multibliz-pos
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn multibliz_pos.wsgi:application --bind 0.0.0.0:$PORT --timeout 30 --workers 1 --worker-class sync --max-requests 1000"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multibliz-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: USE_S3
        value: "True"
      - key: AWS_STORAGE_BUCKET_NAME
        value: "multibliz-pos-media"
      - key: AWS_S3_REGION_NAME
        value: "us-east-1"
